services:
  db:
    image: postgres:15
    container_name: devices_db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: devices_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devicesnet

  api:
    build:
      context: .
      dockerfile: Devicely.Api/Dockerfile
    container_name: devices_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - db
    networks:
      - devicesnet

volumes:
  pgdata:

networks:
  devicesnet:
    driver: bridge
